fix empty post content in Blogger XML causing `lxml.etree.XMLSyntaxError: line 1: b'Tag mn invalid'`
The underlying problem is in HTML checker, a new test is added for it.

Here is a sample traceback with empty post in Blogger XML:

    Traceback (most recent call last):
      File "./linkcheck", line 82, in <module>
        main()
      File "./linkcheck", line 69, in main
        checker.load(args.file, args.json, args.update)
      File "/home/livibetter/p/lnkckr/lnkckr/checkers/base.py", line 109, in load
        self.process(f)
      File "/home/livibetter/p/lnkckr/lnkckr/checkers/blogger.py", line 72, in process
        htmlckr.process(StringIO(content_text))
      File "/home/livibetter/p/lnkckr/lnkckr/checkers/html.py", line 36, in process
        post = html.fromstring(content)
      File "/home/livibetter/.local/lib64/python3.3/site-packages/lxml/html/__init__.py", line 672, in fromstring
        doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
      File "/home/livibetter/.local/lib64/python3.3/site-packages/lxml/html/__init__.py", line 568, in document_fromstring
        value = etree.fromstring(html, parser, **kw)
      File "lxml.etree.pyx", line 2994, in lxml.etree.fromstring (src/lxml/lxml.etree.c:63296)
      File "parser.pxi", line 1617, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:93649)
      File "parser.pxi", line 1488, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:92388)
      File "parser.pxi", line 969, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:88762)
      File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:84804)
      File "parser.pxi", line 676, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:85904)
      File "parser.pxi", line 625, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:85361)
    lxml.etree.XMLSyntaxError: line 1: b'Tag mn invalid'